# Generated by Django 4.2 on 2024-03-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_message_author_id_alter_message_room_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomAdmins',
        ),
    ]
