# Generated by Django 4.2 on 2024-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rules',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
