# Generated by Django 4.2 on 2024-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_media_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
    ]
