# Generated by Django 4.2 on 2024-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_message_has_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomadmin',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
